apiVersion: v1
kind: Service
metadata:
  name: testapp-nofunnel-svc
  labels:
    app: testapp-nofunnel
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: testapp-nofunnel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testapp-nofunnel
  labels:
    app: testapp-nofunnel
spec:
  selector:
    matchLabels:
      app: testapp-nofunnel
  serviceName: testapp-nofunnel-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp-nofunnel
    spec:
      containers:
        - name: testapp
          image: testapp
          env:
            - name: EnableFunnel
              value: 'false'
          ports:
            - containerPort: 8080
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
