apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-funnelenabled
  labels:
    app: testapp-funnelenabled
spec:
  selector:
    matchLabels:
      app: testapp-funnelenabled
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp-funnelenabled
    spec:
      containers:
        - name: testapp
          image: testapp
          env:
            - name: EnableFunnel
              value: 'true'
          ports:
            - containerPort: 8080
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-funnelenabled-svc
  labels:
    app: testapp-funnelenabled
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: testapp-funnelenabled
