load('ext://deployment', 'deployment_yaml', 'service_yaml')

allow_k8s_contexts('k3d-clientintegrationtests')
default_registry('k3d-clientintegrationtests-registry.local.lncd.pl:21345')

# All services needed for tests

local_resource(
  'build-testapp',
  'dotnet publish -o out/testapp ../test/LeanCode.Pipe.ClientIntegrationTestsApp',
  labels=['test-services'],
)

docker_build(
  'testapp',
  '.',
  dockerfile='testapp.dockerfile',
  only = ['out/testapp'],
)

test_services_names = [['disabledfunnel', 'false'], ['enabledfunnel', 'true']]
for test_services_name, funnel_enabled in test_services_names:
  deployment = deployment_yaml(
    'testapp-%s' % test_services_name,
    'testapp',
    port = '8080',
    env = [{ 'name': 'EnableFunnel', 'value': funnel_enabled }],
  )

  service = service_yaml('testapp-%s' % test_services_name, ports = '80:8080')
  k8s_yaml([deployment, service])
  k8s_resource('testapp-%s' % test_services_name, labels=['test-services'])
