allow_k8s_contexts('k3d-clientintegrationtests')
default_registry('k3d-clientintegrationtests-registry.local.lncd.pl:21345')

# All services needed for tests

local_resource(
  'build-testapp',
  'dotnet publish -o out/testapp ../test/LeanCode.Pipe.ClientIntegrationTestsApp',
  labels=['test-services'],
)

docker_build(
  'testapp',
  '.',
  dockerfile='testapp.dockerfile',
  only = ['out/testapp'],
)

k8s_yaml('testapp_funneldisabled.yaml')
k8s_resource('testapp-funneldisabled', labels=['test-services'])

k8s_yaml('testapp_funnelenabled.yaml')
k8s_resource('testapp-funnelenabled', labels=['test-services'])