apiVersion: batch/v1
kind: Job
metadata:
  name: no-scaling-tests
  namespace: no-scaling
  labels:
    app: no-scaling-tests
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: no-scaling-tests
        image: no_scaling_tests
        ports:
          - containerPort: 22
