name: app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  bloc_presentation: ^0.4.0
  collection: ^1.16.0
  cqrs: ^10.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gen: ^5.0.3
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_svg: ^2.0.7
  flutter_web_auth_2: ^3.0.1
  freezed_annotation: ^2.4.1
  go_router: ^9.0.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.7.0
  leancode_contracts: ^0.8.0
  leancode_hooks: ^0.0.6
  leancode_kratos_client:
    git:
      url: git@github.com:leancodepl/leancode_kratos.git
      ref: 3595a81221db4a71b5cce823601da930e773795f
  # leancode_pipe:
  #   git:
  #     url: git@github.com:leancodepl/leanpipe.git
  #     ref: 99409688d249396a8dafb45d9595ac1105d52066
  #     path: dart
  leancode_pipe:
    path: ../
  logging: ^1.0.2
  oauth2: ^2.0.2
  package_info_plus: ^4.1.0
  provider: ^6.0.3
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  word_generator: ^0.4.3

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  custom_lint: ^0.5.3
  flutter_gen_runner: ^5.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.2.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.4
  leancode_contracts_generator:
    git:
      url: git@github.com:leancodepl/contractsgenerator-dart.git
      ref: 5e00962971812531f97be08cf7294f5986b0587e
      path: packages/leancode_contracts_generator
  leancode_lint:
    git:
      url: git@github.com:leancodepl/flutter_corelibrary.git
      ref: afadadeabc4912d06d1926183f6d0aa9fd89f2a4
      path: packages/leancode_lint

dependency_overrides:
  # TODO: remove override when go_router_builder upgrades its deps
  # https://github.com/flutter/flutter/issues/132624
  analyzer: ^6.1.0

flutter:
  uses-material-design: true
  generate: false

flutter_gen:
  output: lib/resources/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_icons:
  # TODO: Replace with real app icon
  image_path: "assets/branding/app_icon.png"
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/branding/fav_icon.png"

flutter_native_splash:
  color: "#ffffff"
  # TODO: Replace with real app icon / other parameters (e.g. background_image)
  image: assets/branding/app_icon.png
  android: true
  ios: true
  web: true

patrol:
  app_name: Leancode Flutter Template
  android:
    package_name: pl.leancode.template
  ios:
    bundle_id: pl.leancode.template
