name: leancode_pipe_example
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  leancode_pipe:
    path: ..
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  logging: ^1.2.0
  dispose_scope: ^2.1.0
  flutter_hooks: ^0.20.1
  leancode_contracts: ^0.8.0
  cqrs: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  leancode_contracts_generator:
    git:
      url: git@github.com:leancodepl/contractsgenerator-dart.git
      ref: feat/leancode_pipe
      path: packages/leancode_contracts_generator

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
