name: leancode_pipe
description: A Dart client for LeanCode's LeanPipe.
homepage: https://github.com/leancodepl/leanpipe/tree/main/dart
repository: https://github.com/leancodepl/leanpipe

version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  http: ^1.1.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  rxdart: ^0.28.0
  signalr_core: ^1.1.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  leancode_lint: ^15.0.0
  mocktail: ^1.0.4
  test: ^1.25.14
