apiVersion: v1
kind: Service
metadata:
  name: testapp2-svc
  labels:
    app: testapp2
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: testapp2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testapp2
  labels:
    app: testapp2
spec:
  selector:
    matchLabels:
      app: testapp2
  serviceName: testapp2-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
        - name: testapp2
          image: testapp2
          ports:
            - containerPort: 8080
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
