apiVersion: v1
kind: Service
metadata:
  name: multiple-services-testapp2-svc
  namespace: multiple-services
  labels:
    app: multiple-services-testapp2
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: multiple-services-testapp2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multiple-services-testapp2
  namespace: multiple-services
  labels:
    app: multiple-services-testapp2
spec:
  selector:
    matchLabels:
      app: multiple-services-testapp2
  serviceName: multiple-services-testapp2-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: multiple-services-testapp2
    spec:
      containers:
        - name: testapp2
          image: testapp2
          env:
            - name: MassTransit__RabbitMq__Url
              value: rabbitmq://guest:guest@rabbitmq-3.rabbitmq-svc.default.svc.cluster.local/
          ports:
            - containerPort: 8080
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
