include('../../publisher/client_integration_tests_cluster/Tiltfile')

docker_build(
  'tests',
  '../',
  dockerfile='../tests.dockerfile'
)

k8s_yaml('tests_disabledfunnel.yaml')
k8s_resource('dart-client-disabledfunnel-tests', resource_deps=['testapp-disabledfunnel'], labels=['tests'])

k8s_yaml('tests_enabledfunnel.yaml')
k8s_resource('dart-client-enabledfunnel-tests', resource_deps=['testapp-enabledfunnel'], labels=['tests'])