include('../../publisher/client_integration_tests_cluster/Tiltfile')

load('ext://deployment', 'job_yaml')

docker_build(
  'tests',
  '../',
  dockerfile='../tests.dockerfile'
)

test_names = ['disabledfunnel', 'enabledfunnel']

for test_name in test_names:
  k8s_yaml(job_yaml(
    'dart-client-%s-tests' % test_name,
    'tests',
    env=[{'name': 'PUBLISHER_HOST', 'value': 'http://testapp-%s-svc.default.svc.cluster.local' % test_name}]
  ))
  k8s_resource('dart-client-%s-tests' % test_name, resource_deps=['testapp-%s' % test_name], labels=['tests'])
