include('../../publisher/client_integration_tests_cluster/Tiltfile')

docker_build(
  'tests',
  'app',
  dockerfile='Dockerfile',
  only = ['out/testapp'], # ??
)

k8s_yaml('tests_funneldisabled.yaml')
k8s_resource('dart-client-funneldisabled-tests', resource_deps=['testapp-funneldisabled'], labels=['tests'])

k8s_yaml('tests_funnelenabled.yaml')
k8s_resource('dart-client-funnelenabled-tests', resource_deps=['testapp-funnelenabled'], labels=['tests'])