apiVersion: v1
kind: Service
metadata:
  name: scaled-target-service-testapp1-svc
  namespace: scaled-target-service
  labels:
    app: scaled-target-service-testapp1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: scaled-target-service-testapp1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scaled-target-service-testapp1
  namespace: scaled-target-service
  labels:
    app: scaled-target-service-testapp1
spec:
  selector:
    matchLabels:
      app: scaled-target-service-testapp1
  serviceName: scaled-target-service-testapp1-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: scaled-target-service-testapp1
    spec:
      containers:
        - name: testapp1
          image: testapp1
          env:
            - name: MassTransit__RabbitMq__Url
              value: rabbitmq://guest:guest@rabbitmq-1.rabbitmq-svc.default.svc.cluster.local/
          ports:
            - containerPort: 8080
            - containerPort: 22
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
