import 'package:app/common/widgets/app_text_field.dart';
import 'package:flutter/material.dart';

class AppTextFormField extends FormField<String> {
  AppTextFormField({
    super.key,
    Widget? label,
    String? hint,
    TextAlign textAlign = TextAlign.start,
    required TextEditingController controller,
    bool obscureText = false,
    bool autocorrect = true,
    bool enableSuggestions = true,
    Iterable<String>? autofillHints = const [],
    TextInputAction? textInputAction,
    TextInputType? keyboardType,
    VoidCallback? onSubmitted,
    Widget? suffixIcon,
    BorderRadius borderRadius = const BorderRadius.all(Radius.circular(8)),
    Color? fillColor,
    bool enableBorder = true,
    CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.start,
    int? minLines,
    int? maxLines = 1,
    int? hintMaxLines,
    bool? enabled,
    required super.validator,
  }) : super(
          initialValue: controller.text,
          builder: (state) => AppTextField(
            label: label,
            error: state.errorText,
            hint: hint,
            textAlign: textAlign,
            controller: controller,
            obscureText: obscureText,
            autocorrect: autocorrect,
            enableSuggestions: enableSuggestions,
            autofillHints: autofillHints,
            textInputAction: textInputAction,
            keyboardType: keyboardType,
            onSubmitted: onSubmitted,
            suffixIcon: suffixIcon,
            borderRadius: borderRadius,
            fillColor: fillColor,
            enableBorder: enableBorder,
            crossAxisAlignment: crossAxisAlignment,
            minLines: minLines,
            maxLines: maxLines,
            hintMaxLines: hintMaxLines,
            enabled: enabled,
            onChanged: state.didChange,
          ),
        );
}
