name: publisher_client_integration_tests
description: Leanpipe publisher and dart client integration test
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  test: ^1.21.0

dev_dependencies:
  lints: ^2.0.0
